import asyncio
import os
import sys
from datetime import datetime
from datetime import datetime
from dotenv import load_dotenv
import markdown
from src.agent import InvestmentAgent

# Load environment variables
load_dotenv()

def convert_md_to_html(content, title):
    """Converts markdown content to a full HTML page."""
    # Strip leading/trailing code blocks if Gemini added them
    clean_content = content.replace("```markdown", "").replace("```", "").strip()
    html_body = markdown.markdown(clean_content, extensions=['fenced_code', 'codehilite'])
    
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1, h2, h3 {{ color: #2c3e50; }}
        code {{ background-color: #f8f9fa; padding: 2px 4px; border-radius: 4px; }}
        pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        blockquote {{ border-left: 4px solid #eee; margin: 0; padding-left: 15px; color: #666; }}
    </style>
</head>
<body>
    {html_body}
</body>
</html>
"""
    return html_content

# List of investments to track
INVESTMENTS = [
    {"name": "PLATIN", "ticker": "PLW00:NYMEX"},
    {"name": "GOLD", "ticker": "GCW00:COMEX"}
]

def generate_markdown(result, investment_name):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"""# {investment_name} Investment Analysis
**Date:** {result.full_date}
**Generated:** {timestamp}

## 💰 Market Status
- **Current Price:** {result.current_price}
- **Outlook:** {result.market_outlook}
- **Trend:** {result.trends_info}
- **Source:** {result.price_source}

## 📋 Executive Summary
{result.summary}

## 📰 Top News
"""
    
    for news in result.top_news:
        url = news.url or "#"
        source = news.source or "Unknown Source"
        md_content += f"- **[{news.title}]({url})** - _{source}_\n"

    md_content += "\n---\n*Generated by InvestmentAnalyst AI*"
    return md_content

async def main():
    print("Starting Investment Analyst Job...")
    agent = InvestmentAgent()
    
    # Ensure base directory exists
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    for inv in INVESTMENTS:
        name = inv["name"]
        ticker = inv["ticker"]
        print(f"Processing: {name}")
        result = await agent.analyze_investment(name, ticker)
        
        if result:
            investment_dir = os.path.join(base_dir, name)
            os.makedirs(investment_dir, exist_ok=True)
            
            filename_md = f"{datetime.now().strftime('%Y-%m-%d')}.md"
            filepath_md = os.path.join(investment_dir, filename_md)
            
            filename_html = f"{datetime.now().strftime('%Y-%m-%d')}.html"
            filepath_html = os.path.join(investment_dir, filename_html)
            
            md_content = generate_markdown(result, name)
            html_content = convert_md_to_html(md_content, f"{name} Investment Analysis")
            
            with open(filepath_md, "w") as f:
                f.write(md_content)

            with open(filepath_html, "w") as f:
                f.write(html_content)
                
            print(f"Report saved to: {filepath_md} and {filepath_html}")
        else:
            print(f"Failed to analyze {investment}")

if __name__ == "__main__":
    asyncio.run(main())
