import asyncio
import os
import sys
from datetime import datetime
from datetime import datetime
from dotenv import load_dotenv
import markdown
from src.agent import InvestmentAgent

# Load environment variables
load_dotenv()

def convert_md_to_html(content, title):
    """Converts markdown content to a full HTML page."""
    # Strip leading/trailing code blocks if Gemini added them
    clean_content = content.replace("```markdown", "").replace("```", "").strip()
    html_body = markdown.markdown(clean_content, extensions=['fenced_code', 'codehilite'])
    
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1, h2, h3 {{ color: #2c3e50; }}
        code {{ background-color: #f8f9fa; padding: 2px 4px; border-radius: 4px; }}
        pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        blockquote {{ border-left: 4px solid #eee; margin: 0; padding-left: 15px; color: #666; }}
    </style>
</head>
<body>
    {html_body}
</body>
</html>
"""
    return html_content

# List of investments to track
INVESTMENTS = [
    {"name": "PLATIN", "ticker": "PLW00:NYMEX"},
    {"name": "GOLD", "ticker": "GCW00:COMEX"}
]

def generate_markdown(result, investment_name):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"""# {investment_name} Investment Analysis
**Date:** {result.full_date}
**Generated:** {timestamp}

## 💰 Market Status
- **Current Price:** {result.current_price}
- **Outlook:** {result.market_outlook}
- **Trend:** {result.trends_info}
- **Source:** {result.price_source}

## 📋 Executive Summary
{result.summary}

## 📰 Top News
"""
    
    for news in result.top_news:
        url = news.url or "#"
        source = news.source or "Unknown Source"
        md_content += f"- **[{news.title}]({url})** - _{source}_\n"

    md_content += "\n---\n*Generated by InvestmentAnalyst AI*"
    return md_content

async def main():
    print("Starting Investment Analyst Job...")
    agent = InvestmentAgent()
    
    # Ensure base directory exists
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    for inv in INVESTMENTS:
        name = inv["name"]
        ticker = inv["ticker"]
        print(f"Processing: {name}")
        result = await agent.analyze_investment(name, ticker)
        
        if result:
            investment_dir = os.path.join(base_dir, name)
            os.makedirs(investment_dir, exist_ok=True)
            
            filename_md = f"{datetime.now().strftime('%Y-%m-%d')}.md"
            filepath_md = os.path.join(investment_dir, filename_md)
            
            filename_html = f"{datetime.now().strftime('%Y-%m-%d')}.html"
            filepath_html = os.path.join(investment_dir, filename_html)
            
            md_content = generate_markdown(result, name)
            html_content = convert_md_to_html(md_content, f"{name} Investment Analysis")
            
            with open(filepath_md, "w") as f:
                f.write(md_content)

            with open(filepath_html, "w") as f:
                f.write(html_content)
                
            print(f"Report saved to: {filepath_md} and {filepath_html}")
        else:
            print(f"Failed to analyze {name}")
            
    # Generate the static index page
    generate_index_page(base_dir)

def generate_index_page(base_dir):
    """Generates an index.html landing page linking to all reports."""
    
    html_header = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Investment Analyst Dept.</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 0; background: #f4f7f6; color: #333; }
        .container { max-width: 1000px; margin: 0 auto; padding: 20px; }
        header { background: #2c3e50; color: white; padding: 2rem 0; text-align: center; margin-bottom: 2rem; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        h1 { margin: 0; font-weight: 300; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin-bottom: 40px; }
        .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); transition: transform 0.2s; }
        .card:hover { transform: translateY(-5px); }
        .card h2 { color: #2c3e50; margin-top: 0; border-bottom: 1px solid #eee; padding-bottom: 10px; }
        .latest-badge { background: #27ae60; color: white; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; float: right; }
        .btn { display: inline-block; background: #3498db; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; margin-top: 10px; }
        .btn:hover { background: #2980b9; }
        table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #eee; }
        th { background: #f8f9fa; font-weight: 600; color: #555; }
        tr:last-child td { border-bottom: none; }
        .section-title { border-left: 5px solid #3498db; padding-left: 15px; margin: 40px 0 20px; color: #2c3e50; }
        footer { text-align: center; padding: 20px; color: #7f8c8d; font-size: 0.9em; margin-top: 50px; }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Investment Analyst Dept.</h1>
            <p>Daily AI-Driven Commodity Market Intelligence</p>
        </div>
    </header>
    <div class="container">
    """

    cards_html = "<h2 class='section-title'>Latest Reports</h2><div class='grid'>"
    archives_html = "<h2 class='section-title'>Archives</h2><table><thead><tr><th>Asset</th><th>Date</th><th>Link</th></tr></thead><tbody>"

    for inv in INVESTMENTS:
        name = inv["name"]
        inv_dir = os.path.join(base_dir, name)
        
        if not os.path.exists(inv_dir):
            continue
            
        # Find all HTML files
        files = [f for f in os.listdir(inv_dir) if f.endswith(".html")]
        files.sort(reverse=True) # Descending Order (Newest first)
        
        if files:
            latest_file = files[0]
            latest_date = latest_file.replace(".html", "")
            
            # Card
            cards_html += f"""
            <div class='card'>
                <span class='latest-badge'>Latest: {latest_date}</span>
                <h2>{name}</h2>
                <p>Market analysis and price updates for {name}.</p>
                <a href='{name}/{latest_file}' class='btn'>Read Report</a>
            </div>
            """
            
            # Archive Rows
            for f in files:
                date_str = f.replace(".html", "")
                archives_html += f"<tr><td><strong>{name}</strong></td><td>{date_str}</td><td><a href='{name}/{f}'>View Report</a></td></tr>"

    cards_html += "</div>"
    archives_html += "</tbody></table>"
    html_footer = "<footer>Generated by InvestmentAnalyst AI · iadept</footer></div></body></html>"
    
    final_html = html_header + cards_html + archives_html + html_footer
    
    index_path = os.path.join(base_dir, "index.html")
    with open(index_path, "w") as f:
        f.write(final_html)
    
    print(f"Index page generated: {index_path}")

if __name__ == "__main__":
    asyncio.run(main())
